name: simsiam_resnet18
dataset:
  name: AID
  image_size: 128
  num_workers: 8

model:
  name: simsiam
  backbone: resnet50
  proj_layers: 2

train:
  optimizer:
    name: sgd
    weight_decay: 0.0005
    momentum: 0.9
  warmup_epochs: 10
  warmup_lr: 0
  base_lr: 0.09
  final_lr: 0
  num_epochs: 100
  stop_at_epoch: 100
  batch_size: 128
  knn_monitor: True
  knn_interval: 10
  knn_k: 200
  train_data_dir: dataset/AID_split/train
  test_data_dir: dataset/AID_split/test

eval:
  optimizer:
    name: sgd
    weight_decay: 0.000
    momentum: 0.9
  warmup_lr: 0
  warmup_epochs: 0
  base_lr: 0.08
  final_lr: 0
  batch_size: 128
  num_epochs: 30
  stop_at_epoch: 30
  train_data_dir: dataset/AID_split/train_linear
  test_data_dir: dataset/AID_split/test

logger:
  tensorboard: False
  matplotlib: False

seed: 1234